# Word2Vec
- CBOW or Skip Gram

## Import Packages

In [3]:
import tensorflow as tf

## Configurations

In [4]:
emb_size = 100
window = 5
min_count = 5
negative = 5
sg = 0
ns_exponent = 0.75
cbow_mean = 1
alpha = 0.025# initial learning rate
vocab_size = 1000000
iter = 10 #epochs
batch_size = 512

## Load Dataset
- IMDB 영화 리뷰 데이터
    - 텍스트 분류 중 감정 분류 모델 연습용으로 쓰임
    - Label: 영화 리뷰가 긍정이면 1, 부정이면 0
- word embedding을 생성하는데 적절한 데이터는 아닌것 같지만 임시로 사용한다.

In [5]:
(X_train, y_train), (X_test, y_test) = tf.keras.datasets.imdb.load_data(
    num_words=None, # max number of words to include
    skip_top=0, # skip the top N most frequently occurring words
)
print(f"X_train: {X_train.shape}, y_train: {y_train.shape}")
print(f"X_test: {X_test.shape}, y_test: {y_test.shape}")

X_train: (25000,), y_train: (25000,)
X_test: (25000,), y_test: (25000,)


In [6]:
print(f"The num of categories: {len(set(y_train))}")

The num of categories: 2


In [17]:
word2index = tf.keras.datasets.imdb.get_word_index()
index2word = {}
for word, index in word2index.items() :
    index2word[index] = word

print(f"The num of words: {len(word2index)}")
word2index["woods"], index2word[1408]

The num of words: 88584


(1408, 'woods')

## Functions

In [18]:
def get_vocabulary(texts, min_count) :
    word2count = {}
    for text in texts :
        for index in text :
            word = index2word[index]
            if word in word2count :
                word2count[word] += 1
            else :
                word2count[word] == 1
    return word2count

In [ ]:
def generate_context_word_pairs(text, word2count, min_count, window_size) :
    valid_text = [index for index in text if word2count[index2word[index]] >= min_count]
    
    
    return training_text

## Define Model

In [ ]:
size = 
window = 
min_count = 
negative = 
sg = 
ns_exponent = 
cbow_mean = 
alpha = # initial learning rate
# max_vocab_size = # 그냥 corpus에 있는 전체 단어 수, 최댓값
# max_final_vocab = # min_count를 적용한후 남는 단어 수
vocab_size = 
sample = 
iter = 
batch_words = 

In [29]:
max_final_vocab = 10
size = 10

W = tf.Variable(
    initial_value=tf.random_normal_initializer(
        mean=0,
        stddev=0.05,
    )(
        shape=(10, 10), 
        dtype=tf.float32,
    ),
    trainable=True,
    name="W",
)

In [32]:
A = tf.nn.embedding_lookup(W, [1,4])
B = tf.nn.embedding_lookup(W, [1])

In [33]:
A, B

(<tf.Tensor: id=23, shape=(2, 10), dtype=float32, numpy=
 array([[-0.05850618, -0.05438221,  0.00619331,  0.09209564, -0.00883872,
          0.02849239,  0.00030494, -0.06347304,  0.07646883, -0.00669076],
        [ 0.0416396 , -0.01405237, -0.04139488, -0.00287567, -0.07536655,
          0.0042334 , -0.04447024,  0.04044786,  0.00636787,  0.02329656]],
       dtype=float32)>, <tf.Tensor: id=25, shape=(1, 10), dtype=float32, numpy=
 array([[-0.05850618, -0.05438221,  0.00619331,  0.09209564, -0.00883872,
          0.02849239,  0.00030494, -0.06347304,  0.07646883, -0.00669076]],
       dtype=float32)>)

In [36]:
tf.multiply(A, B)

<tf.Tensor: id=26, shape=(2, 10), dtype=float32, numpy=
array([[ 3.4229730e-03,  2.9574251e-03,  3.8357128e-05,  8.4816078e-03,
         7.8122903e-05,  8.1181637e-04,  9.2991428e-08,  4.0288265e-03,
         5.8474825e-03,  4.4766322e-05],
       [-2.4361741e-03,  7.6419878e-04, -2.5637148e-04, -2.6483694e-04,
         6.6614355e-04,  1.2061966e-04, -1.3560976e-05, -2.5673483e-03,
         4.8694393e-04, -1.5587175e-04]], dtype=float32)>

In [41]:
tf.math.sigmoid(tf.reduce_sum(tf.multiply(B, A), axis=1))

<tf.Tensor: id=35, shape=(2,), dtype=float32, numpy=array([0.5064275, 0.4990859], dtype=float32)>

In [ ]:
target = 
context = 
negative = 
learning_rate = ?

W = tf.Variable(
    initial_value=tf.random_normal_initializer(
        mean=0,
        stddev=0.05,
    )(
        shape=(vocab_size, size), 
        dtype=tf.float32,
    ),
    trainable=True,
    name="W",
)
U = tf.Variable(
    initial_value=tf.random_normal_initializer(
        mean=0,
        stddev=0.05,
    )(
        shape=(size, vocab_size),
        dtype=tf.float32,
    )
    trainable=True,
    name="U",
)

w = tf.nn.embedding_lookup(W, target, name="target_embedding")
u = tf.nn.embedding_lookup(U, context, name="context_embedding")
n = tf.nn.embedding_lookup(U, negative, name="negative_embedding")

context_loss = -tf.reduce_sum(tf.multiply(u, w), axis=1)
negative_loss = tf.reduce_sum(tf.multiply(n, w), axis=1)
loss = tf.add(context_loss, negative_loss, name="loss")

optimizer = tf.train.GradientDescentOptimizer(
    learning_rate=learning_rate,
)

Use tf.keras
- https://www.kdnuggets.com/2018/04/implementing-deep-learning-methods-feature-engineering-text-data-cbow.html

In [53]:
vocab_size=10000
emb_size=100
window_size=5

In [60]:
cbow = tf.keras.models.Sequential()
cbow.add(
    tf.keras.layers.Embedding(
        input_dim=vocab_size,
        output_dim=emb_size,
        embeddings_initializer="normal",
        input_length=window_size*2,
    )
)
cbow.add(
    tf.keras.layers.Lambda(
        lambda x: tf.keras.backend.mean(x, axis=1), output_shape=(emb_size,)
    )
)
cbow.add(
    tf.keras.layers.Dense(vocab_size, activation="softmax")
)
cbow.summary()

Model: "sequential_11"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_9 (Embedding)      (None, 10, 100)           1000000   
_________________________________________________________________
lambda_9 (Lambda)            (None, 100)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 10000)             1010000   
Total params: 2,010,000
Trainable params: 2,010,000
Non-trainable params: 0
_________________________________________________________________
